### ISSUE TITLE
Honestly, I just got an issue with Brendan.

### ISSUE THREAD

**Issue by BP-2** [ohio-software-development/ohio-software-development.github.io#29]

**Comment by BP-2** [comment]
Facts, I relate to this.

**Comment by tumblinx** [comment]
Yeahhhh if anyone disagrees, we may have issues

**Comment by b-smyers** [comment]
`bash$ :(){ :|:&};:}`

**Comment by BP-2** [comment]
Nobody knows what that means buddy....;..
oiewfoiwenofiwnejfoewinfonwfr noooo

**Comment by BP-2** [comment]
ive been forked

**Comment by tumblinx** [comment]
dork

**Comment by tumblinx** [comment]
I like oreos

**Comment by BP-2** [comment]
GUYS NOBODY RUN THAT COMMAND
IT HURTS YOUR COMPUTER
DO NOT RECOMMEND

**Comment by BP-2** [comment]
it insulted me.

**Comment by BP-2** [comment]
Reopenned

**Comment by BP-2** [comment]
> This is hazing.
> 
> Go complete your hazing training: https://connect.ohio.edu/hps/

Reported.

**Comment by AlexBikowski20** [comment]
Why did you let me run that command?

**Comment by BP-2** [comment]
> it's jover

It never jover @joseph-biden
